### PR TITLE
Fixing staging pipeline

### PR DESCRIPTION
**Pull request by Rolazo**
Modifying pipeline to fix errors

### CODE REVIEW

**Comment by Rolazo** [comment]
@mhmdksh  you help here bro. To reflect the changes in the staging pipeline it must be modified within the master instead of staging.

Once merge, we no longer going to experience these errors -->
[here](https://github.com/Giveth/notification-center/actions/runs/10044793109/job/27761907332)

**Comment by RamRamez** [comment]
@Rolazo The problem is if we merge this to main branch, it won't run because main branch doesn't have yarn.lock yet and it's based on NPM

**Comment by Rolazo** [comment]
@RamRamez so we gotta make main branch to make it work with yarn before approving this

**Comment by RamRamez** [comment]
This problem has been fixed. Thanks @Rolazo

**Pull request closed without merging**
